<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:include filename="inertial_macros.xacro"/>

  <!-- <link name="blank"> -->
    <!-- <visual> </visual> -->
    <!-- <geometry> </geometry> -->
    <!-- <inertial> </inertial> -->
  <!-- </link> -->

  <xacro:property name="chassis_length" value="0.176"/>
  <xacro:property name="chassis_width" value="0.1"/>
  <xacro:property name="chassis_thickness" value="0.003"/>
  <xacro:property name="chassis_tail_length" value="0.0330"/>
  <xacro:property name="chassis_tail_width" value="0.15"/>
  <xacro:property name="chassis_spacing" value="${0.02 + chassis_thickness}"/>
  <xacro:property name="chassis_base_link_offset_z" value="0.047"/>
  <xacro:property name="chassis_wheel_offset_x" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_thickness" value="0.03"/>
  <xacro:property name="wheel_base_link_offset_y" value="0.0675"/>

  <xacro:property name="wheel_mass" value="0.036"/>


  <xacro:property name="caster_wheel_radius" value="0.036"/>
  <xacro:property name="caster_wheel_mass" value="0.036"/>

  <material name="orange">
    <color rgba="1 0.3 0.1 1"/>
  </material>

  <link name="base_link"> </link>

  <!-- BASE_FOOTPRINT LINK -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint"> </link>


  
  <!-- CHASSIS LINK -->
  <joint name="chassis_lower_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_lower"/>
    <origin xyz="${-chassis_wheel_offset_x} 0 ${chassis_base_link_offset_z}"/>
  </joint>

  <link name="chassis_lower">
    <visual>
      <origin xyz="${chassis_tail_length / 2} 0 ${chassis_thickness / 2}"/>
        <!-- TAIL PART -->
        <geometry>
          <box size="${chassis_tail_length} ${chassis_tail_width} ${chassis_thickness}"/>
        </geometry>
    </visual>
    <visual>
      <origin xyz="${chassis_length / 2 + chassis_tail_length} 0 ${chassis_thickness / 2}"/>
        <!-- MAIN PART -->
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
        </geometry>
        <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="${chassis_tail_length / 2} 0 ${chassis_thickness / 2}"/>
        <!-- TAIL PART -->
        <geometry>
          <box size="${chassis_tail_length} ${chassis_tail_width} ${chassis_thickness}"/>
        </geometry>
    </collision>
    <collision>
      <origin xyz="${chassis_length / 2 + chassis_tail_length} 0 ${chassis_thickness / 2}"/>
        <!-- MAIN PART -->
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
        </geometry>
    </collision>

    <xacro:inertial_box mass="0.5" x="${chassis_length + chassis_tail_length}" y="${chassis_tail_width}" z="${chassis_thickness}">
      <origin xyz="${(chassis_length + chassis_tail_length) / 2} 0 ${chassis_thickness/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="chassis_middle_joint" type="fixed">
    <parent link="chassis_lower"/>
    <child link="chassis_middle"/>
    <origin xyz="0 0 ${chassis_spacing}"/>
  </joint>

  <link name="chassis_middle">
    <visual>
      <origin xyz="${chassis_tail_length / 2} 0 ${chassis_thickness / 2}"/>
        <!-- TAIL PART -->
        <geometry>
          <box size="${chassis_tail_length} ${chassis_tail_width} ${chassis_thickness}"/>
        </geometry>
    </visual>
    <visual>
      <origin xyz="${chassis_length / 2 + chassis_tail_length} 0 ${chassis_thickness / 2}"/>
        <!-- MAIN PART -->
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_thickness}"/>
        </geometry>
        <material name="orange"/>
    </visual>
  </link>

  <!-- WHEELS LINK -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_base_link_offset_y} ${wheel_radius}" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_base_link_offset_y} ${wheel_radius}" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${-chassis_wheel_offset_x + 0.19} 0 ${chassis_base_link_offset_z}"/>
  </joint>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
  </link>


</robot>
